# Generated by Django 6.0.3 on 2026-03-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "news_categories",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Слаг"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="Обложка"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликована"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="news.newscategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "db_table": "news",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kg", "Кыргызский"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="news.newscategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод категории",
                "verbose_name_plural": "Переводы категорий",
                "db_table": "news_category_translations",
                "unique_together": {("category", "lang")},
            },
        ),
        migrations.CreateModel(
            name="NewsTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kg", "Кыргызский"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "excerpt",
                    models.TextField(blank=True, verbose_name="Краткое описание"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Контент")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Meta Description"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="news.news",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод новости",
                "verbose_name_plural": "Переводы новостей",
                "db_table": "news_translations",
                "unique_together": {("news", "lang")},
            },
        ),
    ]
