# Generated by Django 6.0.3 on 2026-03-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Сайт"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Партнёр",
                "verbose_name_plural": "Партнёры",
                "db_table": "partners",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PartnerTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kg", "Кыргызский"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="partners.partner",
                        verbose_name="Партнёр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод партнёра",
                "verbose_name_plural": "Переводы партнёров",
                "db_table": "partner_translations",
                "unique_together": {("partner", "lang")},
            },
        ),
    ]
