# Generated by Django 6.0.3 on 2026-03-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("enactus", "Enactus"),
                            ("hult_prize", "Hult Prize"),
                            ("ybi", "YBI"),
                            ("youth_initiatives", "Молодёжные инициативы"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="programs/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "programs",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramAdvisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="programs/advisors/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisors",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_advisors",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="programs/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_gallery",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("university", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="programs/teams/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_teams",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_timeline",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramTimelineTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kg", "Кыргызский"),
                            ("en", "English"),
                        ],
                        max_length=5,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="programs.programtimeline",
                    ),
                ),
            ],
            options={
                "db_table": "program_timeline_translations",
                "unique_together": {("timeline", "lang")},
            },
        ),
        migrations.CreateModel(
            name="ProgramTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kg", "Кыргызский"),
                            ("en", "English"),
                        ],
                        max_length=5,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("instruction", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_translations",
                "unique_together": {("program", "lang")},
            },
        ),
    ]
