# Generated by Django 6.0.3 on 2026-03-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
        migrations.AlterModelOptions(
            name="programadvisor",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Советник",
                "verbose_name_plural": "Советники",
            },
        ),
        migrations.AlterModelOptions(
            name="programgallery",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Галерея",
            },
        ),
        migrations.AlterModelOptions(
            name="programteam",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.AlterModelOptions(
            name="programtimeline",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Этап таймлайна",
                "verbose_name_plural": "Таймлайн",
            },
        ),
        migrations.AlterModelOptions(
            name="programtimelinetranslation",
            options={
                "verbose_name": "Перевод этапа",
                "verbose_name_plural": "Переводы этапов",
            },
        ),
        migrations.AlterModelOptions(
            name="programtranslation",
            options={
                "verbose_name": "Перевод программы",
                "verbose_name_plural": "Переводы программ",
            },
        ),
        migrations.AlterField(
            model_name="program",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="program",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="programs/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("enactus", "Enactus"),
                    ("hult_prize", "Hult Prize"),
                    ("ybi", "YBI"),
                    ("youth_initiatives", "Молодёжные инициативы"),
                ],
                max_length=50,
                verbose_name="Тип программы",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="program",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
        ),
        migrations.AlterField(
            model_name="programadvisor",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="programadvisor",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="programs/advisors/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="programadvisor",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="programadvisor",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advisors",
                to="programs.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programadvisor",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="programgallery",
            name="caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="Подпись"),
        ),
        migrations.AlterField(
            model_name="programgallery",
            name="image",
            field=models.ImageField(
                upload_to="programs/gallery/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="programgallery",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="programs.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programgallery",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="programs/teams/",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название команды"),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="programs.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="programteam",
            name="university",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Университет"
            ),
        ),
        migrations.AlterField(
            model_name="programtimeline",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="programs.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programtimeline",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="programtimeline",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="programtimelinetranslation",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="programtimelinetranslation",
            name="lang",
            field=models.CharField(
                choices=[("ru", "Русский"), ("kg", "Кыргызский"), ("en", "English")],
                max_length=5,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="programtimelinetranslation",
            name="timeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="programs.programtimeline",
                verbose_name="Этап",
            ),
        ),
        migrations.AlterField(
            model_name="programtimelinetranslation",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="content",
            field=models.TextField(blank=True, verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="instruction",
            field=models.TextField(blank=True, verbose_name="Инструкция"),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="lang",
            field=models.CharField(
                choices=[("ru", "Русский"), ("kg", "Кыргызский"), ("en", "English")],
                max_length=5,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Meta Description"
            ),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Meta Title"
            ),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="programs.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programtranslation",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
